var assert = require('assert')
var is = require('../lib/is')

var fn = function(){}
var exp = (666).toExponential()
var hex = 0x1

describe('Arrays', function(){

  it('is.array', function(){
    assert.equal(false, is.array( fn ), 'fn should be false')
    assert.equal(false, is.array( new Date() ), 'new Date() should be false')
    assert.equal(false, is.array( undefined ), 'undefined should be false')
    assert.equal(false, is.array( NaN ), 'NaN should be false')
    assert.equal(false, is.array( null ), 'null should be false')
    assert.equal(false, is.array( true ), 'true should be false')
    assert.equal(false, is.array( false ), 'false should be false')
    assert.equal(false, is.array( Object.create(null) ), 'Object.create(null) should be false')
    assert.equal(false, is.array( Object.create(Object.prototype) ), 'Object.create(Object.prototype) should be false')
    assert.equal(false, is.array( new Object() ), 'new Object() should be false')
    assert.equal(false, is.array( {} ), '{} should be false')
    assert.equal(false, is.array( {foo:"bar"} ), '{foo:"bar"} should be false')
    assert.equal(false, is.array( {length:1} ), '{length:1} should be false')
    assert.equal(true , is.array( new Array() ), 'new Array() should be true ')
    assert.equal(true , is.array( [] ), '[] should be true ')
    assert.equal(true , is.array( ["foo", "bar"] ), '["foo", "bar"] should be true ')
    assert.equal(false, is.array( arguments ), 'arguments should be false')
    assert.equal(false, is.array( "" ), '"" should be false')
    assert.equal(false, is.array( "  " ), '"  " should be false')
    assert.equal(false, is.array( "asdf" ), '"asdf" should be false')
    assert.equal(false, is.array( "1.23" ), '"1.23" should be false')
    assert.equal(false, is.array( "-42" ), '"-42" should be false')
    assert.equal(false, is.array( "-42.01" ), '"-42.01" should be false')
    assert.equal(false, is.array( "-1" ), '"-1" should be false')
    assert.equal(false, is.array( "0" ), '"0" should be false')
    assert.equal(false, is.array( "666" ), '"666" should be false')
    assert.equal(false, is.array( 1.23 ), '1.23 should be false')
    assert.equal(false, is.array( -42 ), '-42 should be false')
    assert.equal(false, is.array( -1 ), '-1 should be false')
    assert.equal(false, is.array( 0 ), '0 should be false')
    assert.equal(false, is.array( 666 ), '666 should be false')
    assert.equal(false, is.array( -exp ), '-exp should be false')
    assert.equal(false, is.array( exp ), 'exp should be false')
    assert.equal(false, is.array( +exp ), '+exp should be false')
    assert.equal(false, is.array( -hex ), '-hex should be false')
    assert.equal(false, is.array( hex ), 'hex should be false')
    assert.equal(false, is.array( +hex ), '+hex should be false')
    assert.equal(false, is.array( -Infinity ), '-Infinity should be false')
    assert.equal(false, is.array( Infinity ), 'Infinity should be false')
    assert.equal(false, is.array( +Infinity ), '+Infinity should be false')
    assert.equal(false, is.array( "-Infinity" ), '"-Infinity" should be false')
    assert.equal(false, is.array( "Infinity" ), '"Infinity" should be false')
    assert.equal(false, is.array( "+Infinity" ), '"+Infinity" should be false')
  })

  it('is.not.array', function(){
    assert.equal(true , is.not.array({foo:'bar'}))
    assert.equal(false, is.not.array(new Array()))
    assert.equal(false, is.not.array([]))
  })

  it('is.arr', function(){
    assert.equal(false, is.arr({foo:'bar'}))
    assert.equal(true , is.arr(new Array()))
  })

  it('is.not.arr', function(){
    assert.equal(true , is.not.arr({foo:'bar'}))
    assert.equal(false, is.not.arr(new Array()))
    assert.equal(false, is.not.arr([]))
  })

})

describe('Arguments', function(){

  it('is.arguments', function(){
    assert.equal(false, is.arguments( fn ), 'fn should be false')
    assert.equal(false, is.arguments( new Date() ), 'new Date() should be false')
    assert.equal(false, is.arguments( undefined ), 'undefined should be false')
    assert.equal(false, is.arguments( NaN ), 'NaN should be false')
    assert.equal(false, is.arguments( null ), 'null should be false')
    assert.equal(false, is.arguments( true ), 'true should be false')
    assert.equal(false, is.arguments( false ), 'false should be false')
    assert.equal(false, is.arguments( Object.create(null) ), 'Object.create(null) should be false')
    assert.equal(false, is.arguments( Object.create(Object.prototype) ), 'Object.create(Object.prototype) should be false')
    assert.equal(false, is.arguments( new Object() ), 'new Object() should be false')
    assert.equal(false, is.arguments( {} ), '{} should be false')
    assert.equal(false, is.arguments( {foo:"bar"} ), '{foo:"bar"} should be false')
    assert.equal(false, is.arguments( {length:1} ), '{length:1} should be false')
    assert.equal(false, is.arguments( new Array() ), 'new Array() should be false')
    assert.equal(false, is.arguments( [] ), '[] should be false')
    assert.equal(false, is.arguments( ["foo", "bar"] ), '["foo", "bar"] should be false')
    assert.equal(true , is.arguments( arguments ), 'arguments should be true')
    assert.equal(false, is.arguments( "" ), '"" should be false')
    assert.equal(false, is.arguments( "  " ), '"  " should be false')
    assert.equal(false, is.arguments( "asdf" ), '"asdf" should be false')
    assert.equal(false, is.arguments( "1.23" ), '"1.23" should be false')
    assert.equal(false, is.arguments( "-42" ), '"-42" should be false')
    assert.equal(false, is.arguments( "-42.01" ), '"-42.01" should be false')
    assert.equal(false, is.arguments( "-1" ), '"-1" should be false')
    assert.equal(false, is.arguments( "0" ), '"0" should be false')
    assert.equal(false, is.arguments( "666" ), '"666" should be false')
    assert.equal(false, is.arguments( 1.23 ), '1.23 should be false')
    assert.equal(false, is.arguments( -42 ), '-42 should be false')
    assert.equal(false, is.arguments( -1 ), '-1 should be false')
    assert.equal(false, is.arguments( 0 ), '0 should be false')
    assert.equal(false, is.arguments( 666 ), '666 should be false')
    assert.equal(false, is.arguments( -exp ), '-exp should be false')
    assert.equal(false, is.arguments( exp ), 'exp should be false')
    assert.equal(false, is.arguments( +exp ), '+exp should be false')
    assert.equal(false, is.arguments( -hex ), '-hex should be false')
    assert.equal(false, is.arguments( hex ), 'hex should be false')
    assert.equal(false, is.arguments( +hex ), '+hex should be false')
    assert.equal(false, is.arguments( -Infinity ), '-Infinity should be false')
    assert.equal(false, is.arguments( Infinity ), 'Infinity should be false')
    assert.equal(false, is.arguments( +Infinity ), '+Infinity should be false')
    assert.equal(false, is.arguments( "-Infinity" ), '"-Infinity" should be false')
    assert.equal(false, is.arguments( "Infinity" ), '"Infinity" should be false')
    assert.equal(false, is.arguments( "+Infinity" ), '"+Infinity" should be false')
  })

  it('is.not.arguments', function(){
    assert.equal(false, is.not.arguments(arguments))
    assert.equal(true , is.not.arguments([]))
  })

  it('is.arg', function(){
    assert.equal(true , is.arg(arguments))
    assert.equal(false, is.arg([]))
  })

  it('is.not.arg', function(){
    assert.equal(false, is.not.arg(arguments))
    assert.equal(true , is.not.arg([]))
  })

})
